export const SURV_PREFIX='_surv';
export const SCAN_NOT_FOUND='SCAN_NOT_FOUND';
export const SCAN_FOUND_AND_IDENTICAL='SCAN_FOUND_AND_IDENTICAL';
export const SCAN_FOUND_WITH_DIFF='SCAN_FOUND_WITH_DIFF';
export const SCAN_FOUND_ERROR='SCAN_FOUND_ERROR';